// <auto-generated />
using System;
using BlazorWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebApp.Migrations
{
    [DbContext(typeof(NegocioContext))]
    partial class NegocioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebApp.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nombre = "Notebooks"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nombre = "Celulares"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("BlazorWebApp.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductoInteres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BlazorWebApp.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("DetallesPedidos");
                });

            modelBuilder.Entity("BlazorWebApp.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("BlazorWebApp.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            CategoriaId = 1,
                            Descripcion = "Notebook ideal para estudiar, trabajar y navegar por internet. Cuenta con buen rendimiento para tareas diarias.",
                            Imagen = "assets/img/portfolio/1.jpg",
                            Nombre = "Notebook Lenovo",
                            Precio = 850000m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 2,
                            CategoriaId = 2,
                            Descripcion = "Celular moderno con buena cámara, gran capacidad de almacenamiento y excelente rendimiento.",
                            Imagen = "assets/img/portfolio/2.jpg",
                            Nombre = "Samsung Galaxy",
                            Precio = 620000m,
                            Stock = 15
                        },
                        new
                        {
                            ProductoId = 3,
                            CategoriaId = 3,
                            Descripcion = "Auriculares gamer con sonido envolvente, micrófono integrado y luces RGB.",
                            Imagen = "assets/img/portfolio/3.jpg",
                            Nombre = "Auriculares Gamer RGB",
                            Precio = 95000m,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("BlazorWebApp.Models.Promocion", b =>
                {
                    b.Property<int>("PromocionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromocionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PorcentajeDescuento")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPromocional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PromocionId");

                    b.ToTable("Promociones");

                    b.HasData(
                        new
                        {
                            PromocionId = 1,
                            Activo = true,
                            Descripcion = "Potencia para trabajar y estudiar. Intel i5 - 16GB RAM - SSD 512GB.",
                            Imagen = "assets/img/portfolio/1.jpg",
                            Orden = 1,
                            PorcentajeDescuento = 15,
                            PrecioPromocional = 850000m,
                            Titulo = "Notebook Lenovo"
                        },
                        new
                        {
                            PromocionId = 2,
                            Activo = true,
                            Descripcion = "Smartphone de última generación con 256GB y cámara de alta calidad.",
                            Imagen = "assets/img/portfolio/2.jpg",
                            Orden = 2,
                            PorcentajeDescuento = 10,
                            PrecioPromocional = 620000m,
                            Titulo = "Samsung Galaxy"
                        },
                        new
                        {
                            PromocionId = 3,
                            Activo = true,
                            Descripcion = "Sonido envolvente, luces RGB y micrófono integrado.",
                            Imagen = "assets/img/portfolio/3.jpg",
                            Orden = 3,
                            PorcentajeDescuento = 20,
                            PrecioPromocional = 95000m,
                            Titulo = "Auriculares Gamer"
                        });
                });

            modelBuilder.Entity("BlazorWebApp.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Activo = true,
                            Email = "admin@electroshop.com",
                            NombreApellido = "Administrador",
                            Password = "admin123",
                            Rol = "Administrador"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Activo = true,
                            Email = "cliente@electroshop.com",
                            NombreApellido = "Cliente Demo",
                            Password = "cliente123",
                            Rol = "Cliente"
                        });
                });

            modelBuilder.Entity("BlazorWebApp.Models.DetallePedido", b =>
                {
                    b.HasOne("BlazorWebApp.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("BlazorWebApp.Models.Producto", b =>
                {
                    b.HasOne("BlazorWebApp.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BlazorWebApp.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BlazorWebApp.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
